spring.application.name=vianova-ui
server.port=8081
vianova.api.base-url=http://localhost:8080
spring.servlet.multipart.enabled=false
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-http-form-post-size=100MB
server.tomcat.max-swallow-size=100MB
